### ISSUE TITLE
wrong date "fomat" - episode pubDate

### ISSUE THREAD

**Issue by Cooper-Dale** [jeckman/mixcloud-rss-download#11]
i have problem with line, or previous lines of code 
`<pubDate>". date(DATE_RSS,$pubDate) ."</pubDate>` 
because it generates wrong dates, for example 

> <pubDate>Thu, 01 Jan 1970 01:00:00 +0100</pubDate>

and my podcast downloader **gPodder** have problem with date _range/value_ and returns 

> mktime argument out of range

i do not need right date, however it needs some fixes, or deletion of line with that code

**Comment by voidet** [comment]
I can have a look at that today @Cooper-Dale

**Comment by voidet** [comment]
Resolved: https://github.com/jeckman/mixcloud-rss-download/pull/10

**Comment by jeckman** [comment]
Thanks @voidet
