### ISSUE TITLE
Incorporation into RSS-Bridge

### ISSUE THREAD

**Issue by TwizzyDizzy** [jeckman/mixcloud-rss-download#13]
Hi John,

first: thanks for your script! I was wondering, whether you heard of

  https://github.com/RSS-Bridge/rss-bridge

Basically, it has the same goal as you: getting back RSS where it was stripped. There are several bridges that scrape content off of a multitude of pages (see the "bridges" subfolder).

I was wondering, whether you would be willing to incorporate your mixcloud rss-downloader into RSS-Bridge?

Would be great to have it as a bridge!

Cheers
Thomas

**Comment by TwizzyDizzy** [comment]
I'm now suggesting it directly to the RSS-Bridge community.

Cheers
Thomas

**Comment by jeckman** [comment]
I'm all for it - though mixcloud-rss-download is GPLv2 and RSS Bridge looks to be public domain and incorporating MIT licensed code. 

I'd be happy to contribute bits I wrote under MIT for them - though we'd also need permission from any other contributor (I think there's only been one)

**Comment by TwizzyDizzy** [comment]
Hi there!

actually - by now I'm not quite sure whether this is still needed. @chemel implemented "our" (read: RSS-Bridge) bridge in https://github.com/RSS-Bridge/rss-bridge/pull/437.

I don't know if he actually used code from your project or just let himself inspire by it or whether he wrote it completely from scratch. In the former case (copy), this would probably create a problem, in the second case (inspire) an attribution might be in order, in the latter case (rewritten) this is totally independent. But then again, I'm not well versed in the application of licenses.

Maybe he or you could shed some light on that.

I, personally, only use RSS-Bridge, so this issue here might as well be closed, as I now have a Bridge to fetch Mixcloud content.

Cheers
Thomas

**Comment by jeckman** [comment]
Thanks Thomas.
