### ISSUE TITLE
Get per-episode description

### ISSUE THREAD

**Issue by jeckman** [jeckman/mixcloud-rss-download#2]
Right now it just shoves the episode title into the description. 

At the user page, which lists their casts, you don't get more than the title. (See http://www.mixcloud.com/TWR/). I could fetch and parse each individual episode while in the foreach loop, but we're talking ~24 more requests just to generate the feed.

**Comment by atillay** [comment]
I solved this issue (see other comment), i think the only remaining issue is Mixcloud download speed limit.

**Comment by jeckman** [comment]
Closed based on @alexandretillay pull request
