### ISSUE TITLE
Mixcloud items limit

### ISSUE THREAD

**Issue by atillay** [jeckman/mixcloud-rss-download#3]
Hi, your script works great but i found an issue. Mixcloud only displays the first 24 casts on the profil page so the generated rss don't get all the casts if you have more than 24 casts.
--- EDIT ---
I did a few modifications on your code and i'm now able to get all podcasts.

**Comment by jeckman** [comment]
Care to share the modifications?

**Comment by atillay** [comment]
http://alexandretillay.fr/uploads/limit-fix.zip

**Comment by jeckman** [comment]
Merged in these changes - thanks.

**Comment by atillay** [comment]
I found other issues but solved them:
- UTF-8 problem: $my_podcast_page = mb_convert_encoding($my_podcast_page, 'HTML-ENTITIES', "UTF-8");
- Get each cloudcast description: $e_description = json_decode( curlGet('http://api.mixcloud.com'.$episode_info->item(0)->getAttribute("m-url")) ); $e_description = $e_description->description;
- I created a XML file from $output but the file was corrupted, I added <[CDATA[]]> on different tags and it fixed the problem

**Comment by jeckman** [comment]
Any interest in making these changes into a pull request, so I can credit you when merging them in?
