### ISSUE TITLE
Updated code?

### ISSUE THREAD

**Issue by mthornto88** [jeckman/mixcloud-rss-download#9]
Hi John, this code is no longer working as is. Is there an update somewhere?  I tried fixing it and noticed all the urls were pointing to http when it looks like mixcloud is using https now. That gets farther but errors out on the $episode block on finding the elements.

**Comment by jeckman** [comment]
Hey mthornto88 - thanks for the note. I've not been using this for a while, so it sounds like it has become out of date. 

Unfortunately I've not got much time right now to revisit - happy to accept patches from anyone who does, and will if I find time, but that isn't likely.

**Comment by voidet** [comment]
Please see for working updates https://github.com/jeckman/mixcloud-rss-download/pull/10

**Comment by jeckman** [comment]
Merged in @voidet  code - @mthornto88  please try that
